---
apiVersion: skaffold/v1beta17
kind: Config
build:
  artifacts:
    - image: liftbridge
      context: .
      docker:
        dockerfile: k8s/Dockerfile.k8s
    - image: natsboard
      context: dev/
      docker:
        dockerfile: Dockerfile.natsboard
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
deploy: {}

profiles:
  - name: dev
    build:
      local:
        push: false
    deploy:
      kubeContext: kubernetes-admin@kind
      kustomize:
        path: ./k8s/dev
