version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/liftbridge-io/liftbridge
    steps:
      - checkout
      - run: sudo apt-get update -yqq && sudo apt-get install -yqq bzr
      - run: GO111MODULE=on go test -v -coverprofile=coverage.txt ./...
      - codecov/upload:
          file: coverage.txt
