version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"

    steps:
      - checkout
      - run: sudo apt-get update -yqq && sudo apt-get install -yqq bzr
      - run: go get github.com/mattn/goveralls
      - run: go test -v .
      - run: go test -v -coverprofile=coverage.txt ./server/...
      - run: goveralls -coverprofile=coverage.txt -service=circle-ci -repotoken=$COVERALLS_REPO_TOKEN
