---
host: 0.0.0.0
port: '5050'
data:
  dir: "/foo"
batch:
  max:
    messages: '10'
  wait:
    time: '1s'
metadata:
  cache:
    max:
      age: '1m'
log:
  level: 'debug'
  recovery: 'true'
stream:
  retention:
    max:
      bytes: '1024'
      messages: '100'
      age: '1h'
  cleaner:
    interval: '1m'
  segment:
    max:
      bytes: '64'
  roll:
    time: '1m'
  compact: 
    compact: 'true'
    max:
      goroutines: '2'
clustering:
  server:
    id: foo
  namespace: bar
  raft:
    snapshot:
      retain: '10'
      threshold: '100'
    cache:
      size: '5'
    bootstrap:
      peers:
        - a
        - b
    logging: 'true'
  replica:
    max:
      lag:
        time: 1m
      leader:
        timeout: 30s
      idle:
        wait: 2s
    fetch:
      timeout: 3s
  min:
    insync:
      replicas: '1'
nats:
  servers:
  - nats://localhost:4222
